################################################################################

project:
  type: website
  pre-render: "__assets/r/resource_generator.r"
  output-dir: docs

################################################################################

website:
  title: "Miles Moran" 
  favicon: "__assets/images/icon.png"
  navbar:
    left:
      - text: "About"
        href: index.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Resources"
        file: resources.qmd
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/miles-m-moran/
      - icon: github
        href: https://github.com/milesmoran
      - icon: envelope-fill
        href: mailto:miles.moran@oregonstate.edu
  # sidebar:
  #   - id: blog
  #     collapse-level: 2
  #     contents: 
  #     - resources.qmd
  #     border: true

################################################################################

format:
  html:
    theme: 
      - flatly
      - "__assets/css/boot-styles.scss"
    css: "__assets/css/styles.css"
    toc: true
    monofont: "DejaVu Sans Mono"
    monofontoptions: Scale=0.8
    # html-math-method: "mathjax"
    include-in-header:
      # - file: "__assets/latex/mathjaxGreek.html"
      - file: "__assets/latex/commands.qmd"
    grid:
      sidebar-width: 250px  # default: 250px
      body-width: 800px     # default: 800px
      margin-width: 250px   # default: 250px
      gutter-width: 1.5rem  # default: 1.5em

highlight-style: "__assets/other/Miles-textmate.theme"
code-block-bg: "#FAFAFA"
code-block-border-left: "#81B29A"

callout-appearance: default
callout-icon: false

################################################################################

# filters: 
# - webr
# webr:
# - packages: ['tidyverse', 'magrittr'] # Install R packages on document open

# filters:
  # - collapse-callout   # allows use of `collapse-callout` option
  # - pseudocode         # allows use of pseudocode "language" in code chunk
# THESE AREN'T WORKING RIGHT NOW. COME BACK LATER?
# collapse-callout:
#   tip: true
#   note: true
#   warning: true
#   caution: true

################################################################################